services:
  build_armel:
    build:
      context: .
      dockerfile: Dockerfile.arm
    volumes:
      - "..:/build"
      - "../build.armel:/out"
    user: "${UID}:${GID}"
  build_armhf:
    build:
      context: .
      dockerfile: Dockerfile.arm
    volumes:
      - "..:/build"
      - "../build.armhf:/out"
    user: "${UID}:${GID}"
  build_aarch64:
    build:
      context: .
      dockerfile: Dockerfile.arm
    volumes:
      - "..:/build"
      - "../build.aarch64:/out"
    user: "${UID}:${GID}"
  build_amd64:
    build:
      context: .
      dockerfile: Dockerfile.arm
    volumes:
      - "..:/build"
      - "../build.amd64:/out"
    user: "${UID}:${GID}"
