services:
  build_armel:
    build:
      context: .
      dockerfile: Dockerfile.arm
    volumes:
      - "..:/build"
      - "../build.armel:/out"
  build_armhf:
    build:
      context: .
      dockerfile: Dockerfile.arm
    volumes:
      - "..:/build"
      - "../build.armhf:/out"
  build_aarch64:
    build:
      context: .
      dockerfile: Dockerfile.arm
    volumes:
      - "..:/build"
      - "../build.aarch64:/out"
